#
# Module manifest for module 'cLegacyFirewall'
#
# Generated by: Andrew Pearce
#
# Generated on: 03 June 2014
#

@{

# Version number of this module.
ModuleVersion = '1.0'

# ID used to uniquely identify this module
#GUID = '507463e5-9197-450d-89b5-402198b43c5f'

# Author of this module
Author = 'Andrew Pearce'

# Company or vendor of this module
CompanyName = ''

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
NestedModules = @('cLegacyFirewall.psm1')

# Functions to export from this module
FunctionsToExport = '*'

# Cmdlets to export from this module
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module
AliasesToExport = '*'

}

